config/routes.rb
Adventureblog::Application.routes.draw do
  root :to => 'welcome#index'

  match '/test/:test_path' => "qunit#test"

  match '/auth/:provider/callback' => "users#login"
  match '/me' => "admin/users#me", :via => :get, :as => "me", :user_id => "me"
  match '/me/logout' => "users#logout", :as => "logout", :user_id => "me"

  match '/welcome' => "welcome#user", :as => "welcome_user"
  match '/template/:path' => "template#load"
  match "/:user_id/template/:path" => "admin/template#load"
  match '/about' => "static#about"

  resources :countries, :only => [:index]

  resources :users, :path => "", :only => [:edit, :update, :destroy, :new, :create], :controller => "admin/users"
  match '/users/validate_slug' => "users#validate_slug"
  match '/:user_id' => "users#show"
  resources :users, :path => "" do 
    match '/flickr_photoset_photos/:photoset_id' => "admin/users#photoset_photos"
    resources :countries
    resources :locations
    resources :photos, :only => [:edit, :update, :destroy, :new, :create], :controller => "admin/photos" do
      match "reprocess" => "admin/photos#reprocess", :via => "get"
    end
    resources :photos, :only => [:show, :index]
    resources :maps
    resources :posts, :only => [:edit, :update, :destroy, :new, :create], :controller => "admin/posts"
    resources :posts, :only => [:show, :index]
    resources :trips, :only => [:index]
    resources :trips, :only => [:show], :path => "" do
      resources :maps, :only => [:edit, :update, :destroy, :new, :create], :controller => "admin/maps"
      resources :maps, :only => [:show, :index], :controller => "trips/maps"
      resources :locations, :only => [:edit, :update, :destroy, :new, :create], :controller => "admin/locations"
      resources :locations, :only => [:show, :index]
      resources :posts, :only => [:edit, :update, :destroy, :new, :create], :controller => "admin/posts"
      resources :posts, :only => [:show, :index]
      resources :photos, :only => [:edit, :update, :destroy, :new, :create], :controller => "admin/photos"
      resources :photos, :only => [:show, :index]
    end
    resources :trips, :path => "", :only => [:edit, :update, :destroy], :controller => "admin/trips" do
      match '/merge', :via => "post", :action => :merge
    end
    resources :trips, :path => "/trips", :only => [:new, :create], :controller => "admin/trips"
  end
end

app/models/location.rb
class Location < ActiveRecord::Base
 belongs_to :trip
 belongs_to :country
 has_one :user, :through => :trip
 has_many :posts, :order => "day ASC"
 has_and_belongs_to_many :photos
 has_many :statuses, :dependent => :destroy
# validates :slug, :latitude, :longitude, :country_id, :presence => true
 include HasSlug
 include HasDates
 include HasTitle

  def journal_entries_count
    journal_entries.count
  end

  def photos_count
    photos.count
  end

  def smart_title
    return title if title
    geo_string
  end 

  def geo_string
    s = ""
      if( !city.blank? && state )
          s = "#{city}, #{state}"
      elsif (city.blank? && state && country)
          s = "#{state}, #{country_name}"
      elsif (!city.blank? && country)
          s = "#{city}, #{country_name}"
      elsif country
          s = country_name
      end
      s
  end

  def picture
      return GoogleMapPhoto.new(self)
  end

 def country_name
  country.name if country
 end
 
 def self.recent limit = 10
  self.joins(:location_type, :user).order("created_at DESC").limit(limit)
 end

 def self.most_recent_published
   self.joins(:journal_entries, :location_type, :user).order("journal_entries.day DESC").group("journal_entries.location_id")
 end

 def self.with_recent_entries limit = 10
  JournalEntry.joins(:location, :location_type, :user).group(:location_id).order("created_at DESC").limit(limit).collect {|e| e.location }
 end

 def dates
  journal_entries.collect { |entry| entry.day }
 end
  
 def date_range?
  date_range.length > 0
 end
 
 def date_range
  return [] if !journal_entries?
  [journal_entries.first, journal_entries.last].collect { |entry| entry.day }.uniq.compact
 end

 def related limit = 5
  user.random_locations(limit)
 end
 
 def journal_entries?
  journal_entries.length > 0
 end
 
 def teaser
  t = ""
  if t == "" || t.nil?
    entry = journal_entries.where("body IS NOT NULL").order("day ASC").first
    t = Sanitize.clean(entry.body) if !entry.nil?
  end
  t
 end

 private
 def flickr
  @flickr ||= FlickRaw::Flickr.new
 end
end

app/controllers/admin/locations_controller.rb
class Admin::LocationsController < Admin::AdminController
	def destroy
	   @location = current_location
	   @location.destroy
	   render :json => @location
	 end

	 def index
	 	@trip = current_user.trips.find_by_slug(params[:trip_id])
	 	@locations = @trip.locations
	 end

	 def edit
	 	@trip = current_user.trips.joins(:locations).find_by_slug(params[:trip_id])
	 	@location = @trip.locations.find_by_slug(params[:location_id])
	 end

	 def update
	 	location = current_location
	 	location.update_attributes!(params[:location])
	 	location.save!
	 	render :json => location
	 end

	 def create
		@location = current_trip.locations.new( params[:location] )
		@location.set_slug!(String.slugify( @location.smart_title ), current_trip.locations)
		@location.save!
		respond_to do |format| 
			format.html { redirect_to request.referrer }
			format.json { render :json => @location }
		end
	 end

	 protected
	 def current_trip
	 	current_user.trips.find_by_slug(params[:trip_id])
	 end
	 def current_location
	 	current_trip.locations.find_by_slug(params[:id])
	 end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
 helper_method :current_location_type

 def index
  @user = User.find_by_slug(params[:user_id])
  @locations = @user.locations 
  respond_to do |format|
   format.html
   format.json { render :json => @locations }
  end
 end
 
 protected
 def current_location_type
  @user = User.find_by_slug(params[:user_id])
  @location_type ||= @user.location_types.find_by_slug(params[:location_type_id]) 
 end
end

app/helpers/location_helper.rb
module LocationHelper
 def location_link loc, options = {}
  path = location_path loc
  link_to loc.title, path, options.merge({ :class => "location #{loc.location_type.title.downcase}" })
 end

 def location_image loc
 	image loc.photo_url, { :title => loc.title, :alt => loc.title }
 end

 def location_string_parts location
 	s = ""
 	s = "#{s} #{link_to location.title, location_path(location)} in " if location.title
 	s += link_to location.geo_string, location_path(location)
 end

 def location_string_link location
 	s = ""
 	s = "#{s} #{link_to location.title, location_path(location)} in " if location.title
 	s += link_to location.geo_string, location_path(location)
 end

 def location_string location
 	s = ""
 	s = "#{location.title} in " if location.title
 	s += location.geo_string
 end
end

app/views/admin/locations/_photo_uploader.html.erb
<% if current_user.owns?(location) %>
	<section id="photo-upload">
		<header class="autoclear">
			<section id="native-photos">
				<h1>Drag photos</h1>
				<span class="or">Or</span>
				<input type="file" multiple="multiple" />
			</section>
			<section id="third-party-photos">
				<%= render "admin/photos/third_parties" %>
			</section>
		</header>
		
		<div id="photo-container" class="autoclear"></div>
		<footer class="buttons">
			<input type="button" value="Clear" class="button" id="clear-photos" />
			<input type="button" value="Import Photos" class="button" id="save-photos" />
		</footer>
	</section>
<% end %>

app/views/admin/locations/edit.html.erb
<%= render "admin/global/breadcrumb", :trip => @trip, :page => "Edit #{@location.smart_title}" %>
<article id="location" class="form" data-json="<%= @location.to_json %>" data-trip="<%= @location.trip.to_json %>">
	<h1><input type="text" id="location-title" class="edit-title" value="<%= @location.title %>" /></h1>
	<h2 id="location-geo"><%= @location.geo_string %></h2>
	<form>
		<figure id="location-map" class="map"></figure>
	</form>
</article>

app/views/admin/locations/edit_photos.html.erb
<section id="location" data-json="<%= @location.to_json %>">
	<h1 id="page-title">Manage photos</h1>
	<%= link_to "Add photos", new_location_photos_path(@location) %>
	<p id="server-messages"></p>
	<section id="location-photos" data-json="<%= @location.photos.to_json %>">
		<% @location.photos.each do |photo| %>
			<figure class="photo" id="photo-<%= photo.id %>">
				<div class="image-wrapper">
					<a class="remove">X</a>
					<img src="<%= photo.url %>" width="200" w />
				</div>
				<figcaption>
					<input type="text" value="<%= photo.title %>" placeholder="Title" class="title" />
					<textarea placeholder="Description" class="description"><%= photo.description %></textarea>
				</figcaption>
			</figure>
		<% end %>
		<% if @location.photos.count > 0 %>
			<footer class="buttons">
				<input type="button" class="save" value="Save photos for <%= @location.to_s %>" />
			</footer>
		<% end %>
	</section>
</section>

app/views/admin/locations/index.html.erb
<div id="trip">
	<%= render "admin/global/breadcrumb", :trip => @trip, :page => "All Locations" %>
	<%= render "admin/global/create_new_link",
		:url => edit_trip_locations_path(:trip_id => @trip.slug),
		:text => "Add locations"
		%>
	<section id="trip-locations">
		<% @locations.each do |location| %>
			<article>
				<h1><%= location.smart_title %></h1>
				<img src="<%= location.picture.url %>" width="100" height="100" />
				<%= link_to "Edit", admin_edit_location_path(@trip.slug, location.slug), :class => "edit-link" %>
			</article>
		<% end %>
	</section>
</div>

app/views/admin/locations/new.html.erb
<%= render "admin/global/breadcrumb", :trip => @trip, :page => "Add Location" %>
<article id="location" data-trip="<%= @trip.to_json %>">
	<form>
		<div id="messages"></div>
		<input type="text" class="edit-title" id="location-title" placeholder="Title" />
		<h2 id="location-geo"></h2>
		<figure id="google-map" class="map"></figure>
		<footer class="buttons">
			<input type="submit" class="button" id="location-save" value="Save" />
		</footer>
	</form>
</article>