config/routes.rb
Adventureblog::Application.routes.draw do
  root :to => 'welcome#index'

  match '/test/:test_path' => "qunit#test"

  match '/auth/:provider/callback' => "users#login"
  match '/me' => "admin/users#me", :via => :get, :as => "me", :user_id => "me"
  match '/me/logout' => "users#logout", :as => "logout", :user_id => "me"

  match '/welcome' => "welcome#user", :as => "welcome_user"
  match '/template/:path' => "template#load"
  match "/:user_id/template/:path" => "admin/template#load"
  match '/about' => "static#about"

  resources :countries, :only => [:index]

  resources :users, :path => "", :only => [:edit, :update, :destroy, :new, :create], :controller => "admin/users"
  match '/users/validate_slug' => "users#validate_slug"
  match '/:user_id' => "users#show"
  resources :users, :path => "" do 
    match '/flickr_photoset_photos/:photoset_id' => "admin/users#photoset_photos"
    resources :countries
    resources :locations
    resources :photos, :only => [:edit, :update, :destroy, :new, :create], :controller => "admin/photos" do
      match "reprocess" => "admin/photos#reprocess", :via => "get"
    end
    resources :photos, :only => [:show, :index]
    resources :maps
    resources :posts, :only => [:edit, :update, :destroy, :new, :create], :controller => "admin/posts"
    resources :posts, :only => [:show, :index]
    resources :trips, :only => [:index]
    resources :trips, :only => [:show], :path => "" do
      resources :maps, :only => [:edit, :update, :destroy, :new, :create], :controller => "admin/maps"
      resources :maps, :only => [:show, :index], :controller => "trips/maps"
      resources :locations, :only => [:edit, :update, :destroy, :new, :create], :controller => "admin/locations"
      resources :locations, :only => [:show, :index]
      resources :posts, :only => [:edit, :update, :destroy, :new, :create], :controller => "admin/posts"
      resources :posts, :only => [:show, :index]
      resources :photos, :only => [:edit, :update, :destroy, :new, :create], :controller => "admin/photos"
      resources :photos, :only => [:show, :index]
    end
    resources :trips, :path => "", :only => [:edit, :update, :destroy], :controller => "admin/trips" do
      match '/merge', :via => "post", :action => :merge
    end
    resources :trips, :path => "/trips", :only => [:new, :create], :controller => "admin/trips"
  end
end

app/views/global/_country_field.html.erb
<div class="<%= object_type %>-countries-field countries-field">
	<span><%= object.country_name %></span>
	<datalist id="<%= object_type %>-countries">
		<% Country.all.each do |country| %>
			<option data-json="<%= country.to_json %>" value="<%= country.name %>"></option>
		<% end %>
	</datalist>
</div>

app/views/global/_date_fields.html.erb
<section id="dates" class="edit-dates<%= " end-date-active" if obj.has_date_range? %>">
	<label>Date</label>
	<div class="date-field start" id="<%= type %>-start_date">
		<span><%= obj.date_string %></span>
		<input type="text" />
	</div>
</section>

app/views/global/_facebook.html.erb
<div id="fb-root"></div>
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '<%= social_providers["facebook"]["app_id"] %>', // App ID
      status     : true, // check login status
      cookie     : true, // enable cookies to allow the server to access the session
      xfbml      : true  // parse XFBML
    });

  };

  (function(d){
     var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement('script'); js.id = id; js.async = true;
     js.src = "//connect.facebook.net/en_US/all.js";
     ref.parentNode.insertBefore(js, ref);
   }(document));
</script>

app/views/global/_og_tags.html.erb
<%= tag :meta, "property" => "og:image", "content" => @og_image if @og_image %>
<%= tag :meta, "property" => "og:title", "content" => @og_title if @og_title %>
<%= tag :meta, "property" => "og:description", "content" => @og_description if @og_description %>
<%= tag :meta, "property" => "og:url", "content" => @canonical_url if @canonical_url %>
<meta property="og:site_name" content="TravelAddict" />

app/views/global/_trip_grid.html.erb
<article class="trip content" data-json="<%= trip.to_json %>" data-locations="<%= trip.locations.to_json %>" data-maps="<%= trip.maps.to_json %>">
	<%= link_to user_trip_path(:user_id => trip.user.slug, :id => trip.slug) do %>
	    <% if trip.picture %>
	    	<figure>
	        	<img class="lazy" 
	        		data-src="<%= trip.picture.square(800) %>" 
	        		data-height="<%= trip.picture.height %>"
	        		title="<%= trip.title %>" 
	        		alt="<%= trip.title %>" />
	        </figure>
	    <% end %>
	    <div class="text">
		    <h1><%= trip.title %></h1>
		    <p><%= trip.date_string %></p>
		</div>
	<% end %>
</article>

app/views/global/four_oh_four.erb
Sorry, the page you are looking for couldn't be found